apiVersion: batch/v1
kind: Job
metadata:
  name: spammer
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: spammer
          image: europe-docker.pkg.dev/nord-inf-prod/public-docker-repository/jobfair/spammer:latest
          env:
            - name: SPAMMER_BASE_URL
              value: "http://game-service:80"
            - name: SPAMMER_RPS
              value: "500"
            - name: SPAMMER_DURATION_SECONDS
              value: "60"
            - name: SPAMMER_WARMUP_SECONDS
              value: "60"
            - name: SPAMMER_WARMUP_RPS
              value: "50"